# Generated by Django 3.2 on 2022-04-12 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TbUser',
            fields=[
                ('user_email', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('user_pw', models.CharField(max_length=50)),
                ('user_nick', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'tb_user',
                'managed': False,
            },
        ),
    ]
